<div dir = "rtl"> 

# **بسم الله الرحمن الرحیم**

</div>

<h3 style="direction: rtl; text-align: right;">بردار ستونی</h3>

<p style="direction: rtl; text-align: right;">
به‌ازای یک ماتریس  A ، هرگاه فقط یک ستون داشته باشیم، به آن <strong>بردار ستونی</strong> یا به اختصار «بردار p بعدی» می‌گوییم.
نمایش آن به صورت زیر است:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
A =
\begin{bmatrix}
a_1 \\
\vdots \\
a_p
\end{bmatrix}
$$

</div>

<hr>

<h3 style="direction: rtl; text-align: right;">بردار سطری</h3>

<p style="direction: rtl; text-align: right;">
به‌ازای یک ماتریس، اگر فقط یک <strong>سطر</strong> داشته باشیم، به آن <strong>بردار سطری</strong> یا «بردار q بعدی» گفته می‌شود.  
نمایش آن:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
A' = (a_1, \ldots, a_q)
$$

</div>

<hr>

<h3 style="direction: rtl; text-align: right;">ماتریس مثلثی پایین</h3>

<p style="direction: rtl; text-align: right;">
ماتریس مربعی‌ای را <strong>مثلثی پایین</strong> می‌نامیم که تمام اعضای <strong>بالای قطر اصلی</strong> آن صفر باشند.  
به بیان دیگر، برای ماتریس:

$$ A = (a_{ij})_{p \times p} $$

</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
a_{ij} = 0 \quad \text{if} \; j > i
$$
</div>

<p style="direction: rtl; text-align: right;">
نمایش کلی یک ماتریس مثلثی پایین به صورت زیر است:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
\begin{bmatrix}
\cdot & 0 & 0 & \cdots & 0 \\
\cdot & \cdot & 0 & \cdots & 0 \\
\cdot & \cdot & \cdot & \cdots & 0 \\
\vdots & \vdots & \vdots & \ddots & 0 \\
\cdot & \cdot & \cdot & \cdots & \cdot
\end{bmatrix}
$$

</div>

<hr>

<h3 style="direction: rtl; text-align: right;">ماتریس مثلثی بالا</h3>

<p style="direction: rtl; text-align: right;">
ماتریس مربعی‌ای را <strong>مثلثی بالا</strong> می‌نامیم که تمام اعضای <strong>زیر قطر اصلی</strong> آن صفر باشند.  
یعنی:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
a_{ij} = 0 \quad \text{if} \; i > j
$$
</div>

<p style="direction: rtl; text-align: right;">
نمایش کلی یک ماتریس مثلثی بالا:
</p>

<div style=" text-align: center; margin-top: 10px; margin-bottom: 15px;">

$$
\begin{bmatrix}
\cdot & \cdot & \cdot & \cdots & \cdot \\
0 & \cdot & \cdot & \cdots & \cdot \\
0 & 0 & \cdot & \cdots & \cdot \\
\vdots & \vdots & \vdots & \ddots & \cdot \\
0 & 0 & 0 & \cdots & \cdot
\end{bmatrix}
$$
</div>


<p style="direction: rtl; text-align: right;">
قبلاً دربارهٔ نحوهٔ نگاه کامپیوتر به ماتریس‌ها صحبت کرده‌ایم.  
حالا با فرض اینکه درس قبلی را خوب مطالعه کرده‌اید پیش می‌رویم.
</p>

<p style="direction: rtl; text-align: right;">
اگر بخواهیم ماتریس‌هایی را که در این فصل معرفی کردیم با «پایتون خام» پیاده‌سازی کنیم، برای هرکدام باید الگوریتم جداگانه‌ای بنویسیم و سپس آن را به کد تبدیل کنیم.  
اما خوشبختانه وقتی از کتابخانهٔ <strong>NumPy</strong> استفاده می‌کنیم، کارمان بسیار راحت‌تر می‌شود.
</p>

<p style="direction: rtl; text-align: right;">
البته اینکه شما هر ماتریس را خودتان با پایتون خام پیاده‌سازی کنید، کار بسیار ارزشمندی‌ست؛ چون باعث می‌شود برنامه‌نویسی را عمیق‌تر یاد بگیرید و ذهن الگوریتمی‌تان تقویت شود.  
اما هدف ما در این کتاب، یادگیری «جبر خطی» با کمک پایتون است؛ نه نوشتن همه‌چیز از صفر.  
به همین دلیل، از این مرحله به بعد از توانایی‌های NumPy کمک می‌گیریم.
</p>

<p style="direction: rtl; text-align: right;">
قبل از اینکه سراغ کدنویسی برویم، اجازه بدهید چند تابع برای مباحثی که تا الان مطرح کردیم از NumPy را معرفی کنم؛ توابعی که قرار است زندگی ما را راحت‌تر کنند! 😊  
این چهار تابع عبارت‌اند از:
</p>

<p style="direction: rtl; text-align: right;">
<strong>arange، reshape، tril، triu</strong>
</p>

<h4 style="direction: rtl; text-align: right;">۱) تابع <code>np.arange</code></h4>

<p style="direction: rtl; text-align: right;">
تابع <code>np.arange</code> یک دنبالهٔ عددی پشت‌سرهم تولید می‌کند.  
</p>

<p style="direction: rtl; text-align: right;">
مثال واقعی برای استفاده در جبر خطی:
</p>
<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
# ساخت ماتریس سطری با اعداد 1 تا 9  
A = np.arange(1, 10)
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
# یا ساخت ماتریس 3×3 با اعداد 1 تا 9
A = np.arange(1, 10).reshape(3, 3)
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">۲) تابع <code>reshape</code></h4>

<p style="direction: rtl; text-align: right;">
در جبر خطی، ابعاد بسیار مهم‌اند.  
مثلاً یک بردار باید شکل <span dir="ltr">(n, 1)</span> داشته باشد و یک ماتریس 3×3 باید دقیقاً 3 سطر و 3 ستون داشته باشد.
</p>

<p style="direction: rtl; text-align: right;">
تابع <code>reshape</code> دقیقاً برای «تبدیل ابعاد داده‌ها» استفاده می‌شود.  
داده‌ها همان هستند، اما ساختارشان عوض می‌شود؛ چیزی که در جبر خطی مدام نیاز داریم.
</p>

<ul style="direction: rtl; text-align: right;">
  <li>ساخت بردار ستونی از یک آرایه -> <span dir="ltr">(n -> n×1)</span></li>
  <li>ساخت بردار سطری -> <span dir="ltr">(n -> 1×n)</span></li>
  <li>ساخت ماتریس مربعی -> <span dir="ltr">(n² -> n×n)</span></li>
</ul>

<p style="direction: rtl; text-align: right;">
مثال واقعی:
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
v = np.arange(1, 4)          # [1 2 3]  <br>
col = v.reshape(3, 1)        # بردار ستونی1×3  
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">۳) تابع <code>np.tril</code></h4>

<p style="direction: rtl; text-align: right;">
در جبر خطی، ماتریس‌های «مثلثی پایین» داشتیم؛  
</p>

<p style="direction: rtl; text-align: right;">
تابع <code>np.tril</code> برای ساخت چنین ماتریس‌هایی استفاده می‌شود.  
این تابع از یک ماتریس مربعی یک نسخهٔ مثلثی پایین تولید می‌کند:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>همهٔ عناصر بالا صفر می‌شوند -> <span dir="ltr">(j > i)</span></li>
  <li>فقط قطر و عناصر زیر قطر باقی می‌مانند</li>
</ul>

<p style="direction: rtl; text-align: right;">
مثال:
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
A = np.arange(1, 10).reshape(3, 3)  <br>
L = np.tril(A)
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">۴) تابع <code>np.triu</code></h4>

<p style="direction: rtl; text-align: right;">
ماتریس‌های «مثلثی بالا» را نیز میتوان با دستور ساده‌ایی پیاده سازی کرد.  
</p>

<p style="direction: rtl; text-align: right;">
تابع <code>np.triu</code> از یک ماتریس مربعی نسخهٔ مثلثی بالا می‌سازد:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>عناصر زیر قطر صفر می‌شوند -> <span dir="ltr">(i > j)</span></li>
  <li>فقط قطر و عناصر بالای آن باقی می‌مانند</li>
</ul>

<p style="direction: rtl; text-align: right;">
مثال:
</p>

<p style="
    direction: ltr;
    text-align: left;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 8px;
    border-radius: 6px;
    font-family: monospace;
">
A = np.arange(1, 10).reshape(3, 3)  <br>
U = np.triu(A)
</p>


<table style="width: 100%; border-collapse: collapse; direction: rtl; text-align: right; font-size: 16px;">
  <tr style="background-color: #3a3a3a; color: #e4e4e4;">
    <th style="padding: 10px; border: 1px solid #555;">تابع</th>
    <th style="padding: 10px; border: 1px solid #555;">کاربرد در جبر خطی</th>
    <th style="padding: 10px; border: 1px solid #555;">نمونهٔ استفاده</th>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>np.arange</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      ساخت دنبالهٔ منظم اعداد برای تولید بردار و ماتریس‌های پایه
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.arange(1, 10)
    </td>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>reshape</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      تبدیل آرایهٔ خطی به ماتریس یا بردار با ابعاد دلخواه
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.arange(1, 10).reshape(3, 3)
    </td>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>np.tril</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      ساخت ماتریس مثلثی پایین 
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.tril(A)
    </td>
  </tr>

  <tr>
    <td style="padding: 10px; border: 1px solid #ccc;"><code>np.triu</code></td>
    <td style="padding: 10px; border: 1px solid #ccc;">
      ساخت ماتریس مثلثی بالا 
    </td>
    <td style="padding: 10px; border: 1px solid #ccc; direction: ltr; text-align: left;">
      np.triu(A)
    </td>
  </tr>
</table>


<h3 style="direction: rtl; text-align: right;">تمرین‌های کاربردی با توابع NumPy</h3>

<p style="direction: rtl; text-align: right;">
در این بخش چند تمرین عملی طراحی کرده‌ام که مستقیماً از توابع <code>arange</code>، <code>reshape</code>، <code>tril</code> و <code>triu</code> استفاده می‌کنند و برای تمرین کدنویسی میتوانند مفید باشند.
</p>

<hr>

<h4 style="direction: rtl; text-align: right;">تمرین ۱: ساخت ماتریس 3×4 با اعداد پشت‌سرهم</h4>

<p style="direction: rtl; text-align: right;">
یک ماتریس 3×4 بسازید که درایه‌های آن از 1 تا 12 به ترتیب پر شده باشند.  
این تمرین برای درک ترکیب <code>np.arange</code> و <code>reshape</code> مناسب است.
</p>

<p style="direction: rtl; text-align: right;">
ایده:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>اول یک آرایهٔ 1بعدی از 1 تا 12 با <code>np.arange</code> بسازید.</li>
  <li>بعد آن را با <code>reshape</code> به ماتریس 3×4 تبدیل کنید<br> ازتان میخوام که قبل از اینکه کد جواب را ببینید اول خودتان یک تلاشی در جهت حل سوال بکنید.</li>
</ul>

In [17]:
import numpy as np

# تمرین 1: ساخت ماتریس4×3 با اعداد 1 تا 12

# ساخت آرایه 1بعدی از 1 تا 12
nums = np.arange(1, 13)

# تبدیل به ماتریس4×3
A = nums.reshape(3, 4)

print("matrix A (3×4):")
print(A)

matrix A (3×4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


<hr>

<h4 style="direction: rtl; text-align: right;">تمرین ۲: ساخت بردار ستونی و بردار سطری</h4>

<p style="direction: rtl; text-align: right;">
یک بردار ستونی 5بعدی و یک بردار سطری 5بعدی با درایه‌های 1 تا 5 بسازید.  
در این تمرین تمرکز روی نحوهٔ کنترل شکل آرایه‌ها در جبر خطی است.
</p>

<p style="direction: rtl; text-align: right;">
ایده:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>با <code>np.arange</code> اعداد 1 تا 5 را می‌سازیم.</li>
  <li>برای بردار ستونی: شکل را به <span dir="ltr">(5, 1)</span> تغییر می‌دهیم.</li>
  <li>برای بردار سطری: شکل را به <span dir="ltr">(1, 5)</span> تغییر می‌دهیم.</li>
</ul>

In [18]:
import numpy as np

# تمرین 2: بردار ستونی و سطری 5بعدی

v = np.arange(1, 6)  # آرایه 1بعدی: [1 2 3 4 5]

col_vec = v.reshape(5, 1)  # بردار ستونی (5×1)
row_vec = v.reshape(1, 5)  # بردار سطری (1×5)

print("بردار ستونی (5×1):")
print(col_vec)
print("shape:", col_vec.shape)

print("\nبردار سطری (1×5):")
print(row_vec)
print("shape:", row_vec.shape)

بردار ستونی (5×1):
[[1]
 [2]
 [3]
 [4]
 [5]]
shape: (5, 1)

بردار سطری (1×5):
[[1 2 3 4 5]]
shape: (1, 5)


<hr>

<h4 style="direction: rtl; text-align: right;">تمرین ۳: ساخت ماتریس مثلثی پایین از یک ماتریس دلخواه</h4>

<p style="direction: rtl; text-align: right;">
یک ماتریس مربعی 4×4 بسازید که درایه‌های آن از 1 تا 16 به ترتیب پر شده‌اند، سپس از روی آن ماتریس مثلثی پایین استخراج کنید.  
</p>

<p style="direction: rtl; text-align: right;">
ایده:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>با <code>np.arange</code> و <code>reshape</code> یک ماتریس 4×4 می‌سازیم.</li>
  <li>با <code>np.tril</code> تبدیلش میکنیم به پایین مثلثی.</li>
</ul>

In [19]:
import numpy as np

# تمرین 3: ماتریس مثلثی پایین

# ساخت ماتریس 4×4 با اعداد 1 تا 16
A = np.arange(1, 17).reshape(4, 4)

print("ماتریس A:")
print(A)

# استخراج قسمت مثلثی پایین
L = np.tril(A)

print("\nماتریس مثلثی پایین L:")
print(L)

ماتریس A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

ماتریس مثلثی پایین L:
[[ 1  0  0  0]
 [ 5  6  0  0]
 [ 9 10 11  0]
 [13 14 15 16]]


<h3 style="direction: rtl; text-align: right;">ماتریس قطری</h3>

<p style="direction: rtl; text-align: right;">
این ماتریس یک ویژگی کلیدی دارد:
</p>

<p style="
    direction: rtl;
    text-align: center;
    font-family: monospace;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 10px;
    border-radius: 6px;
    width: 70%;
    margin: auto;
">
به جز درایه‌های روی قطر اصلی، تمام درایه‌های دیگر صفر هستند.
</p>

<p style="direction: rtl; text-align: right;">
یعنی اگر ماتریس را به صورت <span dir="ltr">A[i, j]</span> بنویسیم، فقط زمانی مقدار غیر صفر داریم که:
</p>

<p style="
    text-align: center;
    font-family: monospace;
    width: 200px;
    margin: auto;
">
i == j
</p>

<p style="direction: rtl; text-align: right;">
مثال یک ماتریس قطری 4×4:
</p>

<p style="
    text-align: center;
    font-family: monospace;
    width: 200px;
    margin: auto;
">

$$
\begin{bmatrix}
3 & 0 & 0 & 0 \\
0 & 5 & 0 & 0 \\
0 & 0 & -2 & 0 \\
0 & 0 & 0 & 7
\end{bmatrix}
$$
</p>

<hr>

<h3 style="direction: rtl; text-align: right;">ماتریس واحد</h3>

<p style="direction: rtl; text-align: right;">
ماتریس واحد که معمولاً با نماد <span dir="ltr">I</span> یا <span dir="ltr">I<sub>n</sub></span> شناخته می‌شود، 
این ماتریس یک ویژگی بسیار ساده و مهم دارد:
</p>

<p style="
    direction: rtl;
    text-align: center;
    font-family: monospace;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 10px;
    border-radius: 6px;
    width: 70%;
    margin: auto;
">
روی قطر اصلی همگی 1 هستند  
و تمام درایه‌های دیگر صفر.
</p>

<p style="direction: rtl; text-align: right;">
مثال ماتریس واحد 4×4:
</p>

<p style="
    text-align: center;
    font-family: monospace;
    width: 200px;
    margin: auto;
">

$$
\begin{bmatrix}
1 & 0 & 0 & 0 \\
0 & 1 & 0 & 0 \\
0 & 0 & 1 & 0 \\
0 & 0 & 0 & 1
\end{bmatrix}
$$

</p>

<p style="direction: rtl; text-align: right;">
در جبر خطی، ماتریس واحد همان نقش عدد «۱» در ضرب اعداد را بازی می‌کند.  
همان‌طور که:
</p>

<div style="
    direction: rtl;
    text-align: center;
    font-family: monospace;
    width: 150px;
    margin: auto;
">
<span dir="ltr">

$a \times 1 = a$</span>
<br>
</div>

<p style="direction: rtl; text-align: right;">
در ماتریس‌ها داریم:
</p>

<div style="
    direction: ltr;
    text-align: center;
    font-family: monospace;
    width: 250px;
    margin: auto;
">

<span dir="ltr">

$A \times I = A$</span>
<br>
<span dir="ltr">

$I \times A = A$</span>
</p>
</div>
<hr>


<h3 style="direction: rtl; text-align: right;">ماتریس متقارن</h3>

<p style="direction: rtl; text-align: right;">
این ماتریس وقتی «متقارن» نامیده می‌شود که نسبت به قطر اصلی خودش قرینه باشد.  
یعنی مقدار درایهٔ سطر <span dir="ltr">i</span> و ستون <span dir="ltr">j</span> دقیقاً برابر باشد با مقدار سطر <span dir="ltr">j</span> و ستون <span dir="ltr">i</span>.
</p>

<div style="
    text-align: center;
    font-family: monospace;
    width: 320px;
    margin: auto;
">

$$
A_{ij} = A_{ji}
$$
</div>

<p style="direction: rtl; text-align: right;">
این تعریف دقیقاً یعنی ماتریس نسبت به قطر اصلی خودش «آینه‌ای» است.
</p>

<h3 style="direction: rtl; text-align: right;">یک مثال ساده از ماتریس متقارن</h3>

<p style="direction: rtl; text-align: right;">
در مثال زیر، می‌بینید که درایه‌های بالا و پایین قطر اصلی یکسان‌اند:
</p>

<div style="
    text-align: center;
    font-family: monospace;
    width: 220px;
    margin: auto;
">
    
$$
\begin{bmatrix}
2  & 4  & -1 \\
4  & 3  & 7  \\
-1 & 7  & 5
\end{bmatrix}
$$
</div>
<p style="direction: rtl; text-align: right;">
به عبارتی:
</p>

<div style="
    direction: ltr;
    text-align: center;
    font-family: monospace;
    margin: auto;
">
$A = A^{T}$
</div>

<hr>

<h3 style="direction: rtl; text-align: right;">ماتریس هرمیتی</h3>

<p style="direction: rtl; text-align: right;"> 
این ماتریس‌ها نسخهٔ «مختلط» ماتریس‌های متقارن هستند.
</p>

<p style="direction: rtl; text-align: right;">
یک ماتریس مربعی A را هرمیتی می‌نامیم اگر:
</p>

<div style="
    direction: ltr;
    text-align: center;
    font-family: monospace;
    background-color: #3a3a3a;
    color: #e4e4e4;
    padding: 2px;
    border-radius: 6px;
    width: 280px;
    margin: auto;
">
$A = (A^{T})^{*}$
</div>
<p style="direction: rtl; text-align: right;">
یعنی:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>ابتدا ترانهادهٔ ماتریس را می‌گیریم (جابجایی سطر و ستون).</li>
  <li>بعد هر عدد مختلط را مزدوج می‌کنیم.</li>
  <li>اگر نتیجه دوباره همان ماتریس اولیه بود -> ماتریس «هرمیتی» است.</li>
</ul>

<h3 style="direction: rtl; text-align: right;">تعریف درایه‌ای ماتریس هرمیتی</h3>

<p style="direction: rtl; text-align: right;">
درایه‌های ماتریس هرمیتی این قانون را رعایت می‌کنند:
</p>

<div style="
    text-align: center;
    font-family: monospace;
    margin: auto;
">
$A_{ij} = \overline{A_{ji}}$
</div>

<p style="direction: rtl; text-align: right;">
پس مثل ماتریس متقارن، نسبت به قطر اصلی تقارن دارد،  
اما این تقارن برای اعداد مختلط با مزدوج آن‌ها انجام می‌شود.
</p>

<h3 style="direction: rtl; text-align: right;">یک مثال از ماتریس هرمیتی</h3>

<p style="direction: rtl; text-align: right;">
ماتریس زیر یک ماتریس هرمیتی 3×3 است:
</p>

<div style="
    text-align: center;
    font-family: monospace;
    margin: auto;
">

$$
\begin{bmatrix}
1      & 1 - i  & 2 \\
1 + i  & 3      & i \\
2      & -i     & 1
\end{bmatrix}
$$
</div>

<p style="direction: rtl; text-align: right;">
اگر چک کنید:
</p>

<p style="direction: rtl; text-align: right;">
برای این ماتریس هرمیتی، روابط درایه‌ها به این شکل‌اند:
</p>
<div style="text-align: right;">
    
 - $A_{1,2} = 1 - i$ و مزدوجش $1 + i = A_{2,1}$
 - $A_{2,3} = i$ و مزدوجش $-i = A_{3,2}$
 - درایه‌های روی قطر اصلی همیشه حقیقی هستند.
</div>
<h3 style="direction: rtl; text-align: right;">نکات مهم ماتریس هرمیتی</h3>
<b></b>
<ul style="direction: rtl; text-align: right;">
  <li>درایه‌های روی قطر اصلی همیشه   <b> حقیقی </b>هستند.</li>
  <li>مقادیر ویژهٔ ماتریس هرمیتی همیشه   <b> حقیقی </b> است.</li>
</ul>



<p style="direction: rtl; text-align: right;">
قبل از اینکه سراغ کدنویسی برویم، چند تابع و عملگر مهم در NumPy را که برای ماتریس‌های قطری، واحد، متقارن و هرمیتی لازم داریم معرفی می‌کنیم.
</p>








<hr><hr>
<h4 style="direction: rtl; text-align: right;">۱) تابع <span dir="ltr">np.diag</span> برای ماتریس قطری</h4>

<p style="direction: rtl; text-align: right;">
این تابع دو کاربرد اصلی دارد:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>اگر ورودی‌اش یک بردار باشد -> از روی عناصر آن یک ماتریس قطری می‌سازد.</li>
  <li>اگر ورودی‌اش یک ماتریس باشد -> قطر اصلی آن ماتریس را به صورت یک بردار برمی‌گرداند.</li>
</ul>


In [20]:
import numpy as np

# لیست مقادیر روی قطر
diagonal_values = [3, 5, -2, 7]

# ساخت ماتریس قطری 4×4
D = np.diag(diagonal_values)

print("ماتریس قطری D:")
print(D)

# استخراج دوباره‌ی قطر اصلی همین ماتریس به صورت یک بردار
d = np.diag(D)
print("\nقطر اصلی D به صورت بردار:")
print(d)

ماتریس قطری D:
[[ 3  0  0  0]
 [ 0  5  0  0]
 [ 0  0 -2  0]
 [ 0  0  0  7]]

قطر اصلی D به صورت بردار:
[ 3  5 -2  7]


<hr>
<h4 style="direction: rtl; text-align: right;">۲) تابع <span dir="ltr">np.eye</span> برای ماتریس واحد</h4>

<p style="direction: rtl; text-align: right;">
تابع <span dir="ltr">np.eye(n)</span> یک ماتریس واحد <span dir="ltr">n×n</span> می‌سازد؛ روی قطر همه‌چیز ۱ و بقیه صفر هستند.
</p>


In [21]:
import numpy as np

# اندازه ماتریس واحد
n = 4

# ساخت ماتریس واحد n×n
I = np.eye(n)

print(I)


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


<hr>
<h4 style="direction: rtl; text-align: right;">۳) ترانهاده‌ی ماتریس: <span dir="ltr">A.T</span></h4>
<p style="direction: rtl; text-align: right;">
در کتابخانهٔ NumPy برای محاسبهٔ ترانهاده نیازی به تابع جداگانه یا پیاده‌سازی خاصی نداریم.  
دلیلش این است که هر آرایهٔ چندبعدی در NumPy یک ویژگی (Attribute) به نام <span dir="ltr">T</span> دارد که مستقیماً ترانهادهٔ آن را برمی‌گرداند.  
استفاده از این ویژگی نیز بسیار ساده است؛ کافی است بنویسیم: <span dir="ltr">A.T</span>
</p>

In [22]:
import numpy as np

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print("ماتریس A:")
print(A)

# محاسبه ترانهاده
A_T = A.T

print("\nترانهاده ماتریس A:")
print(A_T)

ماتریس A:
[[1 2 3]
 [4 5 6]]

ترانهاده ماتریس A:
[[1 4]
 [2 5]
 [3 6]]


<hr>

<div style="direction: rtl; text-align: right;">
قبل از آنکه توضیح بدهیم چطور می‌توان یک ماتریس هرمیتی را در پایتون پیاده‌سازی کرد، لازم است ابتدا با نحوهٔ نمایش <strong>اعداد مختلط</strong> در پایتون آشنا شویم.  
در ریاضیات، عدد مختلط به صورت A + Bi نوشته می‌شود که در آن:
</div>

<div style="direction: rtl; text-align: right;">

- بخش حقیقی: A
- بخش موهومی: Bi
</div>

<p style="direction: rtl; text-align: right;">
اما در پایتون برای نمایش بخش موهومی از حرف <strong>j</strong> استفاده می‌کنیم.  
بنابراین <span dir="ltr">i</span> در ریاضیات دقیقاً معادل <span dir="ltr">j</span> در پایتون است.
</p>

<p style="direction: rtl; text-align: right;">
به عنوان مثال:
</p>

$$3 + 2i \quad \longrightarrow \quad 3 + 2j$$

$$-5i \quad \longrightarrow \quad -5j$$

<div style="direction: rtl; text-align: right;">
 
 - <b>نکته</b>: اگر عدد یا ماتریس مختلطی داشته باشیم، مزدوج گرفتن یعنی:
</div>

$$a + bi \;\rightarrow\; a - bi$$



In [23]:
z1 = 3 + 2j
z2 = -5j
z3 = 1 - 4j 

print(z1)
print(z2)
print(z3)

(3+2j)
(-0-5j)
(1-4j)


<hr>
<h4 style="direction: rtl; text-align: right;">۴) مزدوج مختلط: <span dir="ltr">np.conj()</span> یا <span dir="ltr">A.conjugate()</span></h4>

<p style="direction: rtl; text-align: right;">
برای ماتریس هرمیتی نیاز داریم که مزدوج عناصر را بگیریم. در NumPy دو شکل متداول داریم:
</p>


<ul style="direction: rtl; text-align: right;">
  <li><span dir="ltr">np.conj(A)</span></li>
  <li><span dir="ltr">A.conjugate()</span></li>
</ul>

<p style="direction: rtl; text-align: right;">
این دو دقیقاً <strong>یک کار</strong> انجام می‌دهند:  
علامت بخش موهومی اعداد را عوض می‌کنند.
</p>



In [30]:
import numpy as np

z = 3 + 4j
z_conj1 = np.conj(z)
z_conj2 = z.conjugate()

print("z:", z)
print("np.conj(z):", z_conj1)
print("z.conj():", z_conj2)

z: (3+4j)
np.conj(z): (3-4j)
z.conj(): (3-4j)


<hr>
<h3 style="direction: rtl; text-align: right;">مثال ساده و کامل از یک ماتریس هرمیتی در پایتون</h3>

<p style="direction: rtl; text-align: right;">
در این مثال یک ماتریس مختلط می‌سازیم و سپس آن را به یک ماتریس هرمیتی تبدیل می‌کنیم.
</p>

In [25]:
import numpy as np

# ساخت یک ماتریس مختلط 3×3
A = np.array([
    [1+2j,    3-1j,   4],
    [2+1j,    5,      -3j],
    [4,       3+2j,   2]
], dtype=complex)

print("ماتریس اولیه A:")
print(A)

# ساخت ماتریس هرمیتی با فرمول:
# H = (A + A.T.conj()) / 2
H = (A + A.T.conj()) / 2
print("\n Hermiti matric: \n",H)


ماتریس اولیه A:
[[ 1.+2.j  3.-1.j  4.+0.j]
 [ 2.+1.j  5.+0.j -0.-3.j]
 [ 4.+0.j  3.+2.j  2.+0.j]]

 Hermiti matric: 
 [[1. +0.j  2.5-1.j  4. +0.j ]
 [2.5+1.j  5. +0.j  1.5-2.5j]
 [4. +0.j  1.5+2.5j 2. +0.j ]]


<hr>
<div style="direction: rtl; text-align: right;">
تا اینجای کار یاد گرفتیم که چگونه می‌توان یک ماتریس متقارن یا هرمیتی ساخت.  
حالا می‌خواهیم برای تمرین، تابعی طراحی کنیم که اگر یک ماتریس به آن بدهیم، تشخیص دهد آیا ماتریس ما <strong>متقارن</strong> است، <strong>هرمیتی</strong> است، یا هیچ‌کدام نیست.
<p></p>
اما قبل از نوشتن این تابع، باید به یک نکتهٔ مهم در محاسبات کامپیوتری توجه کنیم:
کامپیوتر اعداد اعشاری را دقیقاً همان‌طور که ما روی کاغذ می‌نویسیم ذخیره نمی‌کند.  
برای مثال، روی کاغذ می‌نویسیم:

</div>

<p style="direction: ltr; text-align: center;">
0.1 + 0.2 = 0.3
</p>

<p style="direction: rtl; text-align: right;">
اما کامپیوتر آن را معمولاً به شکل زیر ذخیره می‌کند:
</p>

<p style="direction: ltr; text-align: center;">
0.30000000000000004
</p>

<p style="direction: rtl; text-align: right;">
این تفاوت کوچک باعث می‌شود مقایسهٔ مستقیم ماتریس‌ها با دستور:
</p>

<p style="
    direction: ltr;
    text-align: center;
    background-color: #3a3a3a;
    color: #e4e4e4;
    font-family: monospace;
    padding: 6px;
    border-radius: 6px;
">
A == B
</p>

<p style="direction: rtl; text-align: right;">
در بسیاری از موارد جواب غلط بدهد و ما فکر کنیم ماتریس متقارن یا هرمیتی نیست،  
در حالی که از نظر ریاضی ماتریس ما متقارن یا هرمیتی هست!
</p>

<hr>

<h3 style="direction: rtl; text-align: right;">راه‌حل: استفاده از تابع np.allclose</h3>

<p style="direction: rtl; text-align: right;">
تابع <span dir="ltr">np.allclose</span> بررسی می‌کند که آیا دو ماتریس از نظر عددی <strong>تقریباً برابر</strong> هستند یا نه.  
این تقریب بر اساس یک میزان خطای کوچک (tolerance) انجام می‌شود و برای کار با اعداد اعشاری ضروری است.
</p>

<p style="direction: rtl; text-align: right;">
به زبان ساده:
</p>

<p style="
    direction: ltr;
    text-align: center;
    background-color: #3a3a3a;
    color: #e4e4e4;
    font-family: monospace;
    padding: 6px;
    border-radius: 6px;
">
np.allclose(A, B)  →  True  اگر اختلافشان خیلی کم باشد
</p>

<p style="direction: rtl; text-align: right;">
این تابع دقیقاً همان چیزی است که برای تشخیص متقارن یا هرمیتی بودن لازم داریم.
</p>

<p style="direction: rtl; text-align: right;">
در مثال زیر ماتریسی داریم که از نظر ریاضی باید متقارن باشد،  
اما کامپیوتر آن را متقارن تشخیص نمی‌دهد! مگر آنکه از allclose استفاده کنیم.
</p>


In [27]:
import numpy as np

# ماتریسی که از نظر ریاضی کاملاً متقارن است
A = np.array([
    [1, 0.1 + 0.2],   # کامپیوتر این را دقیق ذخیره نمی‌کند
    [0.3, 2]
])

print("Matrix A:")
print(A)

# مقایسهٔ مستقیم (اشتباه)
print("\nA == A.T  ->", A == A.T)

# مقایسهٔ درست
print("np.allclose(A, A.T) ->", np.allclose(A, A.T))


Matrix A:
[[1.  0.3]
 [0.3 2. ]]

A == A.T  -> [[ True False]
 [False  True]]
np.allclose(A, A.T) -> True


<p style="direction: rtl; text-align: right;">
همان‌طور که می‌بینید:
</p>

<ul style="direction: rtl; text-align: right;">
  <li><span dir="ltr">A == A.T</span> -> False (اشتباه)</li>
  <li><span dir="ltr">np.allclose(A, A.T)</span> -> True (تشخیص درست)</li>
</ul>
</ul>

<h3 style="direction: rtl; text-align: right;">تابع تشخیص ماتریس متقارن و هرمیتی با استفاده از np.allclose</h3>

<p style="direction: rtl; text-align: right;">
در این بخش یک‌سری تابع می‌نویسیم که:
</p>

<ul style="direction: rtl; text-align: right;">
  <li>ابتدا بررسی کنند ماتریس مربعی است یا نه</li>
  <li>با استفاده از <span dir="ltr">np.allclose</span> تشخیص دهند:
    <ul>
      <li>آیا ماتریس <strong>متقارن</strong> است؟</li>
      <li>آیا ماتریس <strong>هرمیتی</strong> است؟</li>
    </ul>
  </li>
  <li>در نهایت یک تابع کلی که بگوید ماتریس از کدام نوع است.</li>
</ul>


In [28]:
import numpy as np

# تابع برای بررسی متقارن بودن ماتریس
def is_symmetric(M, tol=1e-8):
   
    M = np.array(M)

    # اگر مربعی نباشد، نمی‌تواند متقارن باشد
    if M.shape[0] != M.shape[1]:
        return False
    
    """
    ماتریس متقارن است اگر:
    A ≈ A.T
    """
    return np.allclose(M, M.T, atol=tol)


# تابع برای بررسی هرمیتی بودن ماتریس
def is_hermitian(M, tol=1e-8):
    M = np.array(M)

    # اگر مربعی نباشد، نمی‌تواند هرمیتی باشد
    if M.shape[0] != M.shape[1]:
        return False
    
    """
    ماتریس هرمیتی است اگر:
    A ≈ A.T.conj()
    """
    return np.allclose(M, M.T.conj(), atol=tol)


# تابع کلی برای دسته‌بندی نوع ماتریس
def classify_matrix(M, tol=1e-8):
    """
    نوع ماتریس را مشخص می‌کند:
    - not square
    - symmetric
    - Hermitian
    - symmetric (and Hermitian) برای ماتریس‌های حقیقی متقارن
    - neither symmetric nor Hermitian
    """
    M = np.array(M)

    # اگر اصلاً مربعی نباشد
    if M.shape[0] != M.shape[1]:
        return "not square"

    # اگر هرمیتی باشد
    if is_hermitian(M, tol=tol):
        # اگر تمام درایه‌ها حقیقی باشند، این ماتریس هم متقارن است و هم هرمیتی
        if np.isrealobj(M):
            return "symmetric (and Hermitian)"
        return "Hermitian"

    # اگر فقط متقارن (روی اعداد حقیقی) باشد
    if is_symmetric(M, tol=tol):
        return "symmetric"

    # در غیر این صورت
    return "neither symmetric nor Hermitian"


# --------------------- مثال‌ها --------------------- #

# مثال ۱: ماتریس متقارن حقیقی
S = np.array([
    [2, 4, -1],
    [4, 3,  7],
    [-1, 7, 5]
], dtype=float)

# مثال ۲: ماتریس هرمیتی مختلط
H = np.array([
    [1,      1-1j,  2],
    [1+1j,   3,     1j],
    [2,     -1j,    1]
], dtype=complex)

# مثال ۳: ماتریسی که نه متقارن است، نه هرمیتی
N = np.array([
    [1, 2],
    [3, 4]
], dtype=float)

print("Classification of S:", classify_matrix(S))
print("Classification of H:", classify_matrix(H))
print("Classification of N:", classify_matrix(N))


Classification of S: symmetric (and Hermitian)
Classification of H: Hermitian
Classification of N: neither symmetric nor Hermitian


<p style="direction: rtl; text-align: right;">
برای اینکه مطالعهٔ شما عزیزان راحت‌تر باشد، تمام تابع‌ها و ویژگی‌هایی که تا اینجا معرفی کرده‌ایم را در قالب یک جدول منظم جمع‌آوری کرده‌ایم.  
</p>

<table style="width: 100%; border-collapse: collapse; direction: rtl; text-align: right;">
  <thead>
    <tr style="background-color: #3a3a3a; color: #e4e4e4;">
      <th style="border: 1px solid #999; padding: 8px;">نام تابع / ویژگی</th>
      <th style="border: 1px solid #999; padding: 8px;">کاربرد</th>
      <th style="border: 1px solid #999; padding: 8px;">مثال کوتاه</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.array</span></td>
      <td style="border: 1px solid #999; padding: 8px;">ساخت ماتریس یا آرایه چندبعدی</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">A = np.array([[1,2],[3,4]])</span></td>
    </tr>
      <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.arange()</span></td>
      <td style="border: 1px solid #999; padding: 8px;">ساخت دنبالهٔ عددی (برای reshape بسیار کاربردی)</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.arange(6)</span></td>
    </tr>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">reshape()</span></td>
      <td style="border: 1px solid #999; padding: 8px;">تغییر ابعاد آرایه به ماتریس دلخواه</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.arange(6).reshape(2,3)</span></td>
    </tr>
      <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.tril(A)</span></td>
      <td style="border: 1px solid #999; padding: 8px;">برداشتن بخش زیرقطری ماتریس</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.tril(A)</span></td>
    </tr>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.triu(A)</span></td>
      <td style="border: 1px solid #999; padding: 8px;">برداشتن بخش بالاقطری ماتریس</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.triu(A)</span></td>
    </tr>
      <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.identity(n)</span></td>
      <td style="border: 1px solid #999; padding: 8px;">ساخت ماتریس واحد n×n</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.identity(3)</span></td>
    </tr>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.diag([...])</span></td>
      <td style="border: 1px solid #999; padding: 8px;">ساخت ماتریس قطری از یک لیست</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.diag([3,5,-2])</span></td>
    </tr>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">A.T</span></td>
      <td style="border: 1px solid #999; padding: 8px;">ترانهادهٔ ماتریس</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">A.T</span></td>
    </tr>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.conj(A)</span> / <span dir="ltr">A.conjugate()</span></td>
      <td style="border: 1px solid #999; padding: 8px;">گرفتن مزدوج مختلط</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.conj(3+4j) → 3-4j</span></td>
    </tr>
    <tr>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.allclose(A, B)</span></td>
      <td style="border: 1px solid #999; padding: 8px;">بررسی برابر بودن عددی دو ماتریس (با خطای کوچک)</td>
      <td style="border: 1px solid #999; padding: 8px;"><span dir="ltr">np.allclose(A, A.T)</span></td>
    </tr>




  </tbody>
</table>
