<div dir = "rtl"> 

# **بسم الله الرحمن الرحیم**

</div>

<div dir="rtl" style="text-align: right; font-size: 16px; line-height: 1.8;">

<h1>جمع معمولی دو ماتریس</h1>
در جبر خطی، <b>جمع ماتریس‌ها</b> تنها زمانی تعریف می‌شود که هر دو ماتریس هم‌اندازه باشند.  
برای مثال، اگر دو ماتریس زیر را داشته باشیم:

</div>

$$
A, B \in \mathbb{R}^{m \times n}
$$

<div dir="rtl" style="text-align: right; font-size: 16px; line-height: 1.8;">
آن‌گاه جمع آن‌ها ماتریسی با همان ابعاد است که به‌صورت عضو به عضو تعریف می‌شود:

</div>

$$
(A + B)_{ij} = a_{ij} + b_{ij}
$$

<div dir="rtl" style="text-align: right; font-size: 16px; line-height: 1.8;">
به‌عبارت دیگر، جمع ماتریس‌ها یعنی جمع هر درایه (عضو) از ماتریس اول با درایهٔ متناظر از ماتریس دوم.
<h2>مثال عددی</h2>
فرض کنید:

</div>

$$
A =
\begin{bmatrix}
1 & 3 \\
2 & 4
\end{bmatrix},
\qquad
B =
\begin{bmatrix}
5 & -1 \\
0 & 7
\end{bmatrix}
$$

$$
A + B =
\begin{bmatrix}
1+5 & 3-1 \\
2+0 & 4+7
\end{bmatrix}
=
\begin{bmatrix}
6 & 2 \\
2 & 11
\end{bmatrix}
$$

<div dir="rtl" style="text-align: right; font-size: 16px; line-height: 1.8;">
پس نتیجه می‌گیریم که جمع این دو ماتریس برابر است با:

</div>

$$
A + B =
\begin{bmatrix}
6 & 2 \\
2 & 11
\end{bmatrix}
$$

In [2]:
import numpy as np
A = np.array([[1, 3],
              [2, 4]])

B = np.array([[5, -1],
              [0, 7]])

C = A + B
C

array([[ 6,  2],
       [ 2, 11]])

<hr>

<div dir="rtl">

<h1>ضرب معمولی دو ماتریس</h1>

</div>

<div dir="rtl">
فرض کنید دو ماتریس زیر داده شده‌اند:
</div>

$$
A \in \mathbb{R}^{m \times n}, \qquad B \in \mathbb{R}^{n \times q}
$$

$$
AB = C = (c_{ij})_{m \times q}
$$

<div dir="rtl">
درایهٔ سطر i و ستون j در ماتریس C از ضرب سطر i ماتریس A در ستون j ماتریس B به‌دست می‌آید:
</div>

$$
c_{ij} = \sum_{k=1}^{n} a_{ik} b_{kj}
$$

<div dir="rtl">
<hr>
<h2>خواص مهم جمع و ضرب ماتریسی</h2>

</div>

<div dir="rtl">
<b>۱) جابجایی جمع</b> (در صورت هم‌اندازه بودن ماتریس‌ها):
</div>

$$
A + B = B + A
$$

<div dir="rtl">
<b>۲) شرکت‌پذیری جمع</b>:
</div>

$$
A + (B + C) = (A + B) + C
$$

<div dir="rtl">
<b>۳) توزیع‌پذیری ضرب</b>:
</div>

<div dir="rtl">
توزیع‌پذیری ضرب اسکالر نسبت به جمع:
</div>

$$
k(A + B) = kA + kB
$$

<div dir="rtl">
و توزیع‌پذیری ضرب ماتریسی نسبت به جمع:
</div>

$$
A(B + C) = AB + AC
$$

<div dir="rtl">

<h2>مثال عددی از ضرب دو ماتریس</h2>

</div>

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
\qquad
B =
\begin{bmatrix}
0 & 1 \\
5 & 6
\end{bmatrix}
$$

$$
AB =
\begin{bmatrix}
1\cdot 0 + 2\cdot 5 & 1\cdot 1 + 2\cdot 6 \\
3\cdot 0 + 4\cdot 5 & 3\cdot 1 + 4\cdot 6
\end{bmatrix}
=
\begin{bmatrix}
10 & 13 \\
20 & 27
\end{bmatrix}
$$

<div dir="rtl">
</div>



<hr>

<div dir="rtl">
قبل از اینکه وارد کدنویسی شویم، لازم است یک نکتهٔ بسیار مهم دربارهٔ نحوهٔ ضرب دو مجموعه (یا دقیق‌تر، دو آرایه یا ماتریس) در پایتون را توضیح بدهیم.  
در پایتون، به‌خصوص هنگام استفاده از NumPy، دو عملگر (operator) برای ضرب داریم:

- عملگر <b>*</b>  
- عملگر <b>@</b>

<div style="direction: rtl;">این دو عملگر کاملاً با هم متفاوت‌اند و نتایج بسیار متفاوتی تولید می‌کنند.</div>
</div><br>

<div dir="rtl">
<h3>۱) ضرب با عملگر <code>*</code>، ضرب عضو به عضو</h3>
وقتی شما می‌نویسید: A * B
</div>

<div dir="rtl">
پایتون (و دقیق‌تر NumPy) هر عضو ماتریس ( A ) را با عضو متناظر در ماتریس ( B ) ضرب می‌کند.
به این نوع ضرب می‌گویند:
<b>ضرب عنصر به عنصر</b> یا <b>Element-wise multiplication</b>
و این هیچ ربطی به ضرب ماتریسی در جبر خطی ندارد.
</div>

$$
A * B ;=;
\begin{bmatrix}
a_{11} b_{11} & a_{12} b_{12} \\
a_{21} b_{21} & a_{22} b_{22}
\end{bmatrix}
$$

<div dir="rtl">
<h3>۲) ضرب با عملگر <code>@</code>، ضرب ماتریسی واقعی</h3>
وقتی می‌نویسید: A @ B
</div>

<div dir="rtl">
پایتون عملیات واقعی <b>ضرب ماتریسی</b> را مطابق تعریف جبر خطی انجام می‌دهد:
</div>

$$
(AB)*{ij} = \sum*{k=1}^{n} a_{ik} b_{kj}
$$

<div dir="rtl">
یعنی سطرهای (A) در ستون‌های (B) ضرب می‌شوند و حاصل یک ماتریس جدید خواهد بود.
</div>

<div dir="rtl">
فرض کنید داریم:
</div>

$$
A =
\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix},
\qquad
B =
\begin{bmatrix}
0 & 1 \\
5 & 6
\end{bmatrix}
$$

$$
A \cdot B =
\begin{bmatrix}
1\cdot 0 & 2\cdot 1 \\
3\cdot 5 & 4\cdot 6
\end{bmatrix}
=
\begin{bmatrix}
0 & 2 \\
15 & 24
\end{bmatrix}
$$

<div dir="rtl"><b>نتیجهٔ ضرب ماتریسی:</b></div>

$$
A \text{@} B =
\begin{bmatrix}
1\cdot 0 + 2\cdot 5 & 1\cdot 1 + 2\cdot 6 \\
3\cdot 0 + 4\cdot 5 & 3\cdot 1 + 4\cdot 6
\end{bmatrix}
=
\begin{bmatrix}
10 & 13 \\
20 & 27
\end{bmatrix}
$$

<div dir="rtl">
همان‌طور که می‌بینید، دو نوع ضرب نتیجه‌های کاملاً متفاوتی تولید می‌کنند.
بنابراین هنگام کار با ماتریس‌ها همیشه باید دقت کنید که از عملگر درست استفاده کنید.
</div>
</div>

In [3]:
A = np.array([1,23,4])
B = np.array([1,23,4])

print("A*B: ", A*B)
print("A@B: ", A@B)



A*B:  [  1 529  16]
A@B:  546


In [1]:
import numpy as np

# تعریف چند ماتریس نمونه
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[0, 1],
              [5, 6]])

C = np.array([[2, -1],
              [1,  0]])

k = 3  # یک عدد (اسکالر)

# ۱) جابجایی جمع
left_comm = A + B
right_comm = B + A
print("جابجایی جمع:", np.allclose(left_comm, right_comm))

# ۲) شرکت‌پذیری جمع
left_assoc = A + (B + C)
right_assoc = (A + B) + C
print("شرکت‌پذیری جمع:", np.allclose(left_assoc, right_assoc))

# ۳) توزیع‌پذیری ضرب اسکالر نسبت به جمع
left_scalar = k * (A + B)
right_scalar = k * A + k * B
print("توزیع‌پذیری ضرب اسکالر:", np.allclose(left_scalar, right_scalar))

# ۴) توزیع‌پذیری ضرب ماتریسی نسبت به جمع
left_matmul = A @ (B + C)
right_matmul = A @ B + A @ C
print("توزیع‌پذیری ضرب ماتریسی:", np.allclose(left_matmul, right_matmul))

# نمایش خود ضرب AB
print("AB =\n", A @ B)


جابجایی جمع: True
شرکت‌پذیری جمع: True
توزیع‌پذیری ضرب اسکالر: True
توزیع‌پذیری ضرب ماتریسی: True
AB =
 [[10 13]
 [20 27]]


<hr>

<div dir="rtl">

<h1>ضرب عدد در ماتریس</h1>

</div>

<div dir="rtl">
ضرب یک عدد (که به آن <b>اسکالر</b> یا <b>عدد حقیقی</b> می‌گوییم) در یک ماتریس، یکی از ساده‌ترین عملیات‌های جبر خطی است.  
اگر \( k \) یک عدد و \( A \) یک ماتریس باشد، حاصل‌ضرب \( kA \) به این معناست که:
</div>

<div dir="rtl">
<b>تمام درایه‌های ماتریس A را در عدد k ضرب می‌کنیم.</b>
</div>

$$
A =
\begin{bmatrix}
a_{11} & a_{12} \\
a_{21} & a_{22}
\end{bmatrix}
$$

$$
kA =
\begin{bmatrix}
k\,a_{11} & k\,a_{12} \\
k\,a_{21} & k\,a_{22}
\end{bmatrix}
$$



<div dir="rtl">

<h2>مثال عددی</h2>

</div>

<div dir="rtl">
فرض کنید عدد \( k = 3 \) و ماتریس زیر داده شده است:
</div>

$$
A =
\begin{bmatrix}
2 & -1 \\
4 & 0
\end{bmatrix}
$$

<div dir="rtl">
در این صورت:
</div>

$$
3A =
\begin{bmatrix}
3\cdot 2 & 3\cdot (-1) \\
3\cdot 4 & 3\cdot 0
\end{bmatrix}
=
\begin{bmatrix}
6 & -3 \\
12 & 0
\end{bmatrix}
$$



<div dir="rtl">

<h2>خواص ضرب اسکالر در ماتریس</h2>

</div>

<div dir="rtl"><b>۱) توزیع‌پذیری نسبت به جمع:</b></div>

$$
k(A + B) = kA + kB
$$

<div dir="rtl"><b>۲) شرکت‌پذیری نسبت به ضرب اسکالر:</b></div>

$$
(km)A = k(mA)
$$

<div dir="rtl"><b>۳) تعامل با ماتریس همانی:</b></div>

$$
1A = A, \qquad 0A = 0
$$

<div dir="rtl">

<h2>محاسبهٔ ضرب اسکالر در ماتریس با پایتون</h2>

</div>

<div dir="rtl">
در پایتون و کتابخانهٔ NumPy، ضرب اسکالر در ماتریس به‌سادگی با عملگر <code>*</code> انجام می‌شود.
</div>



In [ ]:
import numpy as np

A = np.array([[2, -1],
              [4,  0]])

k = 3

kA = k * A
kA

<hr>
<div dir="rtl">

<h1>توان ماتریس</h1>

</div>

<div dir="rtl">
توان‌دادن به ماتریس برای ماتریس‌های مربعی تعریف می‌شود.  
اگر ماتریس \( A \) از مرتبهٔ \( n \times n \) باشد، می‌توانیم توان‌های آن را به شکل زیر تعریف کنیم:
</div>

$$
A^1 = A
$$

$$
A^2 = A \cdot A
$$

$$
A^3 = A \cdot A \cdot A
$$

<div dir="rtl">
به‌طور کلی:
</div>

$$
A^k = \underbrace{A \cdot A \cdot \ldots \cdot A}_{k\ \text{time}}
$$

<div dir="rtl">
البته این توان‌ها تنها زمانی تعریف می‌شوند که ماتریس مربعی باشد، چون برای ضرب ماتریسی باید تعداد ستون‌های ماتریس سمت چپ با تعداد سطرهای ماتریس سمت راست برابر باشد.
</div>
<br>

<div dir="rtl">

<h2>خواص مهم توان ماتریس</h2>

</div>

<div dir="rtl">
<b>۱) شرکت‌پذیری ضرب</b> باعث می‌شود که توان‌دادن معنا داشته باشد:
</div>

$$
A^k A^m = A^{k+m}
$$

<div dir="rtl">
<b>۲) اگر ماتریس وارون‌پذیر باشد:</b>
</div>

$$
A^{-k} = (A^{-1})^k
$$

<div dir="rtl">
<b>۳) توان صفر به‌صورت پیش‌فرض تعریف می‌شود:</b>
</div>

$$
A^0 = I
$$

<div dir="rtl">
که I ماتریس همانی (واحد) است.
</div>
<br>

<div dir="rtl">

<h2>مثال عددی</h2>

</div>

$$
A=
\begin{bmatrix}
1 & 1 \\
0 & 1
\end{bmatrix}
$$

<div dir="rtl">
توان دوم:
</div>

$$
A^2 =
A\cdot A =
\begin{bmatrix}
1 & 1 \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 1 \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
1 & 2 \\
0 & 1
\end{bmatrix}
$$

<div dir="rtl">
توان سوم:
</div>

$$
A^3 =
A^2\cdot A =
\begin{bmatrix}
1 & 2 \\
0 & 1
\end{bmatrix}
\begin{bmatrix}
1 & 1 \\
0 & 1
\end{bmatrix}
=
\begin{bmatrix}
1 & 3 \\
0 & 1
\end{bmatrix}
$$

---
<div dir="rtl">
در پایتون برای محاسبهٔ توان ماتریس می‌توانیم از تابع <code>np.linalg.matrix_power(A, k)</code>
استفاده کنیم.
</div>

In [ ]:

import numpy as np

A = np.array([[1, 1],
              [0, 1]])

# توان دوم
A2 = np.linalg.matrix_power(A, 2)

# توان سوم
A3 = np.linalg.matrix_power(A, 3)

print("A^2 =\n", A2)
print("A^3 =\n", A3)


<hr>
<div dir="rtl">

<h1>اثر ماتریس (Trace)</h1>

</div>

<div dir="rtl">
اثر یک ماتریس مربّع را مجموع عناصر روی قطر اصلی ماتریس می‌گویند.  
این مقدار را با نشانه‌های <code>tr(A)</code> یا <code>trace(A)</code> نمایش می‌دهند.
</div>

$$
\mathrm{tr}(A)
= a_{11} + a_{22} + \ldots + a_{nn}
$$

$$
\mathrm{tr}(A)
= \sum_{i=1}^{n} a_{ii}
$$

<div dir="rtl">
در این رابطه، نماد زیر عناصر روی قطر اصلی ماتریس هستند و اثر فقط برای ماتریس‌های مربّع تعریف می‌شود.
</div>

$$
a_{ii}
$$
<br>

<div dir="rtl">

<h2>مثال</h2>
فرض کنید ماتریس زیر را داریم:
</div>

$$
A =
\begin{bmatrix}
3 & 2 & 1 \\
4 & 1 & -1 \\
0 & 5 & 2
\end{bmatrix}
$$

<div dir="rtl">
عناصر قطری این ماتریس عبارت‌اند از:
</div>

$$
3,\quad 1,\quad 2
$$

<div dir="rtl">
پس اثر ماتریس برابر است با:
</div>

$$
\mathrm{tr}(A) = 3 + 1 + 2 = 6
$$

<br>
<hr>
<div dir="rtl">
تابع <code>np.trace</code> در numpy مقدار اثر ماتریس را محاسبه می‌کند.
</div>


In [ ]:
import numpy as np

A = np.array([[3, 2, 1],
              [4, 1, -1],
              [0, 5,  2]])

trace_A = np.trace(A)
trace_A

<hr>
<div dir="rtl">

<h1>افراز ماتریس</h1>

</div>

<div dir="rtl">
گاهی برای ساده‌تر نوشتن یا تحلیل یک ماتریس بزرگ، آن را به چند بلوک کوچک‌تر تقسیم می‌کنیم.  
به این کار <b>افراز ماتریس</b> یا <b>Partitioning</b> گفته می‌شود.
</div>

<div dir="rtl">
اگر ماتریس مربّع یا مستطیلی بزرگ A را به چهار بلوک تقسیم کنیم، آن را چنین نمایش می‌دهیم:
</div>

$$
A =
\begin{bmatrix}
A_{11} & A_{12} \\
A_{21} & A_{22}
\end{bmatrix}
$$

<div dir="rtl">
در این نمایش:
</div>

<div dir="rtl">
- بلوک زیر بخش بالا-چپ ماتریس است:
</div>

$$
A_{11}
$$

<div dir="rtl">
- بلوک زیر بخش بالا-راست ماتریس است:
</div>

$$
A_{12}
$$

<div dir="rtl">
- بلوک زیر بخش پایین-چپ ماتریس است:
</div>

$$
A_{21}
$$

<div dir="rtl">
- بلوک زیر بخش پایین-راست ماتریس است:
</div>

$$
A_{22}
$$

<br>

<div dir="rtl">

<h2>مثال</h2>
فرض کنید ماتریس زیر را داریم:
</div>

$$
A =
\begin{bmatrix}
1 & 2 & 1 & 2 \\
3 & 4 & 3 & 4 \\
5 & 6 & 7 & 8
\end{bmatrix}
$$

<div dir="rtl">
اگر بخواهیم این ماتریس را از وسط به دو قسمت چپ و راست افراز کنیم،  
می‌توانیم آن را به صورت زیر بنویسیم:
</div>

$$
A =
\left[
\begin{array}{c|c}
A_{11} & A_{12}
\end{array}
\right]
$$

<div dir="rtl">
که در آن:
</div>

$$
A_{11} =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
5 & 6
\end{bmatrix}
\qquad
A_{12} =
\begin{bmatrix}
1 & 2 \\
3 & 4 \\
7 & 8
\end{bmatrix}
$$

<br>

<div dir="rtl">

<h2>افراز کامل چهار بلوکی</h2>

</div>

<div dir="rtl">
اگر ردیف‌ها و ستون‌ها را هرکدام یک‌بار جدا کنیم، ماتریس را به ۴ بلوک تقسیم می‌کنیم:
</div>

$$
A =
\begin{bmatrix}
A_{11} & A_{12} \\
\hline
A_{21} & A_{22}
\end{bmatrix}
$$

<div dir="rtl">
که بسته به محل بریدن ردیف‌ها و ستون‌ها، اندازهٔ بلوک‌ها مشخص می‌شود.
</div>

<br>

<div dir="rtl">
به همین روش می‌توان ردیف‌ها را نیز جدا کرد و افراز چهاربخشی ساخت.
</div>



In [8]:
import numpy as np

A = np.array([
    [1, 2, 1, 2],
    [3, 4, 3, 4],
    [5, 6, 7, 8]
])

# افراز ستون‌ها
A11 = A[:, :2]   # دو ستون اول
A12 = A[:, 2:]   # دو ستون آخر

A11, A12

(array([[1, 2],
        [3, 4],
        [5, 6]]),
 array([[1, 2],
        [3, 4],
        [7, 8]]))